# Generated by Django 3.1.7 on 2021-12-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyxav', '0003_bankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20, null=True)),
                ('hours', models.CharField(max_length=20, null=True)),
                ('rate', models.CharField(max_length=20, null=True)),
                ('total', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('invoice_no', models.CharField(max_length=20, null=True)),
                ('projectname_dept', models.CharField(max_length=20, null=True)),
                ('project_description', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
