# Generated by Django 3.1.7 on 2021-11-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(default='resume', upload_to=''),
            preserve_default=False,
        ),
    ]
